import type { Metadata } from "next";
import SupabaseListener from "../repository/supabase-listener";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
