import type { Metadata } from "next";
import "./globals.css";
import NavigationSupabaseListener from "../repository/navigation-supabase-listener";
import Head from "next/head";
// import { biz_udGothic400, biz_udGothic700 } from "../../utils/fonts/fonts";

export const metadata: Metadata = {
  title: "Satella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("RootLayout");

  return (
    <html
      lang='ja'
      // className={`${biz_udGothic400.className}`}
    >
      <Head children={undefined}></Head>
      <body>
        <div>
          <NavigationSupabaseListener />
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
